import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\prsht.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\mshtml.idl";
import "c:\program files\microsoft visual studio .net 2003\vc7\platformsdk\include\dimm.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\mshtmhst.idl";
import "c:\program files\microsoft visual studio .net 2003\vc7\platformsdk\include\docobj.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\exdisp.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\objsafe.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	helpstring("IComponentRegistrar Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\glvisualization\\compreg.h"
interface IComponentRegistrar : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\glvisualization\\compreg.h"
	[id(1)] HRESULT  Attach([in] BSTR bstrPath);
	[id(2)] HRESULT  RegisterAll();
	[id(3)] HRESULT  UnregisterAll();
	[id(4)] HRESULT  GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)] HRESULT  RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT  UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(B1D47447-E686-41A7-9A02-6BC3CCFF0269),
	dual,
	helpstring("IGL3D Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\glvisualization\\gl3d.h"
interface IGL3D : IDispatch {
};


[ version(1.0), uuid(7C814E07-7943-4389-96D9-A9F74F88EB22), custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a, "{587BC862-099F-4C1C-B051-A193B0D28DFD}"), helpstring("GLVisualization 1.0 Type Library") ]
library GLVisualization
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

	[
		version(1.0),
		uuid(587BC862-099F-4C1C-B051-A193B0D28DFD),
		helpstring("ComponentRegistrar Class")
	] 
#line 33 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\glvisualization\\compreg.h"
	coclass CCompReg {
		interface IComponentRegistrar;
	};

	[
		uuid(F37FCEE2-A358-41D1-BF3F-D19CAA7F7D01),
		helpstring("_IGL3DEvents Interface")
	] 
#line 26 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\glvisualization\\gl3d.h"
	dispinterface _IGL3DEvents {
	properties:

	methods:
	};

	[
		version(1.0),
		uuid(F0160158-6F4D-4AD0-AC2B-C5773E2A1754),
		helpstring("GL3D Class")
	] 
#line 42 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\glvisualization\\gl3d.h"
	coclass CGL3D {
		interface IGL3D;
		[default, source]	interface _IGL3DEvents;
	};

}

