using System.Collections.Generic;
using DSIS.Core.Builders;
using DSIS.IntegerCoordinates.Tests;
using NUnit.Framework;

namespace DSIS.IntegerCoordinates.Test
{
  [TestFixture]
  public class CellConnectionAdapterTwoDimTest : CellConnectionAdapterTestBase
  {
    private IntegerCoordinateSystem myIcs;

    private void DoTestAbstract(DoBuild bld, string assert)
    {
      double[] sleft = {0, 0};
      double[] sright = {10, 10};
      long[] sgrid = {10, 10};

      IntegerCoordinateSystem ics = new IntegerCoordinateSystem(
        new MockSystemSpace(2, sleft, sright, sgrid)
        );

      myIcs = ics;
      List<IntegerCoordinate> data = DoTest(ics, bld);

      TwoDimCoordinateAssert.Assert(ics, data, assert);
      myIcs = null;
    }

    private void DoTestAddCellToRect(double[] left, double[] right, string assert)
    {
      double[] eps = {0, 0};

      DoTestAbstract(
        delegate(ICellConnectionBuilder<IntegerCoordinate> ad)
          {
            IRectProcessor<IntegerCoordinate> ps = myIcs.ProcessorFactory.CreateRectProcessor(eps);
            
            ad.ConnectToMany(null, ps.ConnectCellToRect(left, right));
          }, assert);
    }

    private void DoTestAddCellToPoint(double[] point, double[] perc, string assert)
    {
      DoTestAbstract(
        delegate(ICellConnectionBuilder<IntegerCoordinate> ad)
          {
            IRadiusProcessor<IntegerCoordinate> ps = myIcs.CreateRadiusProcessor();
             ad.ConnectToMany(null, ps.ConnectCellToRadius(point, perc));
          },
        assert);
    }

    [Test]
    public void Test_01()
    {
      DoTestAddCellToRect(new double[] {0, 0}, new double[] {10, 10},
                          @"-------------------
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
-------------------
");
    }


    [Test]
    public void Test_02()
    {
      DoTestAddCellToRect(new double[] {1, 0}, new double[] {2, 2},
                          @"-------------------
..........
xxx.......
xxx.......
..........
..........
..........
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_03()
    {
      DoTestAddCellToRect(new double[] {0.01, 0.02}, new double[] {0.01, 0.02},
                          @"-------------------
x.........
..........
..........
..........
..........
..........
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_04()
    {
      DoTestAddCellToPoint(new double[] {0.001, 0.0002}, new double[] {0.1, 0.2},
                           @"-------------------
x.........
..........
..........
..........
..........
..........
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_05()
    {
      DoTestAddCellToPoint(new double[] {1.001, 1.0002}, new double[] {0.1, 0.2},
                           @"-------------------
xx........
xx........
..........
..........
..........
..........
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_06()
    {
      DoTestAddCellToPoint(new double[] {1.901, 1.0002}, new double[] {0.1, 0.1},
                           @"-------------------
..........
xx........
xx........
..........
..........
..........
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_07()
    {
      DoTestAddCellToPoint(new double[] {5, 5}, new double[] {0.1, 0.1},
                           @"-------------------
..........
..........
..........
..........
....xx....
....xx....
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_08()
    {
      DoTestAddCellToPoint(new double[] {5, 5}, new double[] {0, 0},
                           @"-------------------
..........
..........
..........
..........
..........
.....x....
..........
..........
..........
..........
-------------------
");
    }
  }
}