import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\prsht.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\mshtml.idl";
import "c:\program files\microsoft visual studio .net 2003\vc7\platformsdk\include\dimm.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\mshtmhst.idl";
import "c:\program files\microsoft visual studio .net 2003\vc7\platformsdk\include\docobj.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\exdisp.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\objsafe.idl";

[
	object,
	uuid(285691E1-BFC9-4E8B-BE17-5B1CC2302ED9),
	dual,
	helpstring("IActionBase Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionbase.h"
interface IActionBase : IDispatch {
};

[
	object,
	uuid(92F4EEEF-602A-496D-8067-5184F4F1D37B),
	dual,
	helpstring("IResultBase Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\resultbase.h"
interface IResultBase : IDispatch {
};

[
	object,
	uuid(4D5B2A01-1CC2-4D56-A8D7-67C730A057ED),
	dual,
	helpstring("IResultMerger Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\resultmerger.h"
interface IResultMerger : IDispatch {
#line 18 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\resultmerger.h"
	[id(31)] HRESULT  AddResult([in] IResultBase *result);
#line 21 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\resultmerger.h"
	[id(32)] HRESULT  CanAddResult([in] IResultBase *result, [out,retval] VARIANT_BOOL *value);
#line 24 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\resultmerger.h"
	[id(33)] HRESULT  CreateResult([out,retval] IResultBase **result );
};

[
	object,
	uuid(9B7D45A5-77FD-4E97-8C4A-76D3610CC875),
	dual,
	helpstring("IResult Interface"),
	pointer_default(unique)
] 
#line 16 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\result.h"
interface IResult : IResultBase {
#line 19 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\result.h"
	[id(1)] HRESULT  GetResultMerger([out,retval] IResultMerger **merger );
};

[
	object,
	uuid(5EB44493-8FF9-486A-8ABD-09B9F232628A),
	dual,
	helpstring("IActionManager Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionmanager.h"
interface IActionManager : IDispatch {
#line 18 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionmanager.h"
	[id(1)] HRESULT  GetLength([in] int *count);
#line 20 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionmanager.h"
	[id(2)] HRESULT  GetAction([in] int index, [out,retval] IActionBase **action );
};

[
	object,
	uuid(16C62C7B-6775-4D2B-9BD2-43624E01738B),
	dual,
	helpstring("IParameters Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\parameters.h"
interface IParameters : IDispatch {
};

[
	object,
	uuid(54E003E2-EAA0-4321-9A14-31CF8E5BCB84),
	dual,
	helpstring("IProgressBarInfo Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\progressbarinfo.h"
interface IProgressBarInfo : IDispatch {
};

[
	object,
	uuid(B94E10D8-08BD-405C-A435-0868DD86CD3C),
	dual,
	helpstring("IAction Interface"),
	pointer_default(unique)
] 
#line 18 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\action.h"
interface IAction : IActionBase {
#line 21 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\action.h"
	[id(1)] HRESULT  GetNextActionManager([out,retval] IActionManager **manager );
#line 23 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\action.h"
	[id(2)] HRESULT  SetActionParameters([in] IParameters *parameters);
#line 25 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\action.h"
	[id(3)] HRESULT  Do([in] IResult *input, [out,retval] IResult **output );
#line 27 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\action.h"
	[id(4)] HRESULT  SetProgressBarInfo([in] IProgressBarInfo *pinfo);
#line 29 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\action.h"
	[id(5)] HRESULT  IsChainLeaf([out,retval] VARIANT_BOOL *result);
};

[
	object,
	uuid(D3BEDA0D-1771-4493-BB5C-E93384792B2A),
	dual,
	helpstring("INode Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\node.h"
interface INode : IDispatch {
#line 18 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\node.h"
	[id(1)] HRESULT  GetActionManager([out,retval] IActionManager **manager );
#line 20 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\node.h"
	[id(2)] HRESULT  GetResult([out,retval] IResult **result );
};

[
	object,
	uuid(35F624D3-EB6C-4F79-AB1E-C01795A08C5A),
	dual,
	helpstring("IActionFactory Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionfactory.h"
interface IActionFactory : IDispatch {
#line 18 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionfactory.h"
	[id(1)] HRESULT  CanCreateActionFromNode([in] INode *node, [out,retval] VARIANT_BOOL *result);
#line 21 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionfactory.h"
	[id(2),helpstring("Try to create action for such node. Returns NULL is it's imposible")] HRESULT  CreateActionFromNode([in] INode *node, [out,retval] IActionBase **action );
#line 24 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionfactory.h"
	[id(3)] HRESULT  CanCreateActionFromAction([in] IActionBase *action, [out,retval] VARIANT_BOOL *result);
#line 27 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionfactory.h"
	[id(4)] HRESULT  CreateActionFromAction([in] IActionBase *action, [out,retval] IActionBase **result );
};

[
	object,
	uuid(9D90D301-E998-4229-98C0-27C59690308D),
	dual,
	helpstring("IActionAllocator Interface"),
	pointer_default(unique)
] 
#line 20 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionallocator.h"
interface IActionAllocator : IDispatch {
#line 23 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionallocator.h"
	[id(1)] HRESULT  AllocateActionManagerForNode([in] INode *node, [out,retval] IActionManager **manager );
#line 25 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionallocator.h"
	[id(2)] HRESULT  AllocateActionManagerForAction([in] IActionBase *action, [out,retval] IActionManager **manager );
};

[
	object,
	uuid(BC2B7099-B5A6-4D0B-BDE0-DA027E87FF93),
	dual,
	helpstring("IActionAllocator Interface"),
	pointer_default(unique)
] 
#line 36 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionallocator.h"
interface IWritableActionAllocator : IDispatch {
#line 38 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionallocator.h"
	[id(12)] HRESULT  RegisterActionFactory([in] IActionFactory *action);
};

[
	object,
	uuid(E20C06D8-1C51-455C-B306-33D0635F1E52),
	dual,
	helpstring("IActionManagerImpl Interface"),
	pointer_default(unique)
] 
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionmanagerimpl.h"
interface IWritableActionManager : IDispatch {
#line 20 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionmanagerimpl.h"
	[id(11)] HRESULT  AddAction([in] IActionBase *action);
};

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	helpstring("IComponentRegistrar Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\compreg.h"
interface IComponentRegistrar : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\compreg.h"
	[id(1)] HRESULT  Attach([in] BSTR bstrPath);
	[id(2)] HRESULT  RegisterAll();
	[id(3)] HRESULT  UnregisterAll();
	[id(4)] HRESULT  GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)] HRESULT  RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT  UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(0641C669-B362-48C9-8B73-D02B6E252A9D),
	dual,
	helpstring("IGraphInfo Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
interface IGraphInfo : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
	[id(1)] HRESULT  GetNodes([out,retval] int *value);
#line 19 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
	[id(2)] HRESULT  GetEdges([out,retval] int *value);
#line 21 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
	[id(3)] HRESULT  GetDimension([out,retval] int *value);
#line 23 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
	[id(4)] HRESULT  GetMinimum([in] int index, [out,retval] double *value);
#line 25 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
	[id(5)] HRESULT  GetMaximum([in] int index, [out,retval] double *value);
#line 27 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
	[id(6)] HRESULT  GetGridNumber([in] int index, [out,retval] int *value);
#line 29 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
	[id(7)] HRESULT  GetGridSize([in] int index, [out,retval] double *value);
};

[
	object,
	uuid(5F89F9F3-AB8D-4129-A752-8A4258A8ECE9),
	dual,
	helpstring("IWritableGraphInfo Interface"),
	pointer_default(unique),
	local,
	hidden
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writablegraphinfo.h"
interface IWritableGraphInfo : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writablegraphinfo.h"
	[id(12),local,hidden] HRESULT  AddGraph([in] void **graph );
};

[
	object,
	uuid(6E606370-04E2-4BCB-852C-313A7D4BAD15),
	dual,
	helpstring("IGraphResult Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphresult.h"
interface IGraphResult : IResult {
#line 19 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphresult.h"
	[id(10),local,hidden] HRESULT  GetGraph([in] int index, [out] void **graph );
#line 22 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphresult.h"
	[id(11)] HRESULT  GetCount([out,retval] int *count);
#line 24 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphresult.h"
	[id(12)] HRESULT  GetGraphInfo([out,retval] IGraphInfo **info );
#line 26 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphresult.h"
	[id(13)] HRESULT  GetGraphInfoAt([in] int index, [out,retval] IGraphInfo **info );
#line 28 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphresult.h"
	[id(14)] HRESULT  IsStrongComponent([out,retval] VARIANT_BOOL *value);
};

[
	object,
	uuid(6ED8D0EA-3E9C-441A-96C6-EEB2AFCBE27D),
	dual,
	helpstring("IWritableGraphResult Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writablegraphresult.h"
interface IWritableGraphResult : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writablegraphresult.h"
	[id(20),local,hidden] HRESULT  AddGraph([in] void **graph , [in] VARIANT_BOOL isStrongComponent);
};

[
	object,
	uuid(28EBA211-E2B0-4717-87AA-63A0A5C76CDC),
	dual,
	helpstring("IGroupNode Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\groupnode.h"
interface IGroupNode : IDispatch {
#line 18 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\groupnode.h"
	[id(11)] HRESULT  GetLength([out,retval] int *count);
#line 21 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\groupnode.h"
	[id(12)] HRESULT  GetNode([in] int index, [out,retval] INode **node );
#line 24 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\groupnode.h"
	[id(13)] HRESULT  CanAddNode([in] INode *node);
#line 27 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\groupnode.h"
	[id(14)] HRESULT  AddNode([in] INode *node);
#line 30 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\groupnode.h"
	[id(15)] HRESULT  CreateNode([out,retval] INode **node );
};

[
	object,
	uuid(F2D78B39-D782-49DE-91B7-771CDA2ED0E0),
	dual,
	helpstring("IKernell Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\kernell.h"
interface IKernell : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\kernell.h"
	[id(1)] HRESULT  GetActionAllocator([out,retval] IActionAllocator **allocator );
};


[ version(1.0), uuid(922445B5-C296-49D0-B69D-45FF70F8CE56), custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a, "{84035475-16DE-4504-ABF2-5C734E46A96A}"), helpstring("MorseKernel2 1.0 Type Library") ]
library MorseKernel2
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

	[
		version(1.0),
		uuid(43EAE42D-D986-4DAB-9D7D-D4B725E77AB0),
		helpstring("ActionAllocator Class")
	] 
#line 54 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionallocator.h"
	coclass CActionAllocator {
		interface IActionAllocator;
		interface IWritableActionAllocator;
	};

	[
		version(1.0),
		uuid(860DAF52-F263-4F92-A8BE-673E99A9959F),
		helpstring("ActionManagerImpl Class")
	] 
#line 36 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionmanagerimpl.h"
	coclass CActionManagerImpl {
		interface IActionManager;
		interface IWritableActionManager;
	};

	[
		version(1.0),
		uuid(84035475-16DE-4504-ABF2-5C734E46A96A),
		helpstring("ComponentRegistrar Class")
	] 
#line 33 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\compreg.h"
	coclass CCompReg {
		interface IComponentRegistrar;
	};

	[
		version(1.0),
		uuid(1FCB1E52-C321-4E44-8BA6-83DA8C532365),
		helpstring("GraphInfoImpvffffl Class")
	] 
#line 23 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfoimpl.h"
	coclass CGraphInfoImpl {
		interface IWritableGraphInfo;
		interface IGraphInfo;
	};

	[
		version(1.0),
		uuid(43037E6F-9884-4D5C-BB41-44D582888F9E),
		helpstring("GraphResultImpl Class")
	] 
#line 26 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphresultimpl.h"
	coclass CGraphResultImpl {
		interface IWritableGraphResult;
		interface IGraphResult;
		interface IResult;
		interface IResultBase;
		interface IResultMerger;
	};

	[
		uuid(7458F939-BE83-4246-8AB8-0E26B56D34F3),
		helpstring("_IKernellEvents Interface")
	] 
#line 28 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\kernell.h"
	dispinterface IKernellEvents {
	properties:

	methods:
	};

}

