import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\prsht.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\mshtml.idl";
import "c:\program files\microsoft visual studio .net 2003\vc7\platformsdk\include\dimm.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\mshtmhst.idl";
import "c:\program files\microsoft visual studio .net 2003\vc7\platformsdk\include\docobj.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\exdisp.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\objsafe.idl";

[
	object,
	uuid(285691E1-BFC9-4E8B-BE17-5B1CC2302ED9),
	dual,
	helpstring("IActionBase Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\actionbase.h"
interface IActionBase : IDispatch {
};

[
	object,
	uuid(16C62C7B-6775-4D2B-9BD2-43624E01738B),
	dual,
	helpstring("IParameters Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\parameters.h"
interface IParameters : IDispatch {
};

[
	object,
	uuid(54E003E2-EAA0-4321-9A14-31CF8E5BCB84),
	dual,
	helpstring("IProgressBarInfo Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\progressbarinfo.h"
interface IProgressBarInfo : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\progressbarinfo.h"
	[id(1)] HRESULT  Length([out,retval] int *length);
#line 19 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\progressbarinfo.h"
	[id(2)] HRESULT  Next();
#line 21 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\progressbarinfo.h"
	[id(3)] HRESULT  NeedStop([out,retval] VARIANT_BOOL *stop);
#line 23 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\progressbarinfo.h"
	[id(4)] HRESULT  Start();
#line 25 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\progressbarinfo.h"
	[id(5)] HRESULT  Finish();
};

[
	object,
	uuid(92F4EEEF-602A-496D-8067-5184F4F1D37B),
	dual,
	helpstring("IResultBase Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\resultbase.h"
interface IResultBase : IDispatch {
};

[
	object,
	uuid(5498E339-8014-4366-9092-13EB8AD35E1D),
	dual,
	helpstring("IResultSet Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\resultset.h"
interface IResultSet : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\resultset.h"
	[id(1)] HRESULT  GetCount([out,retval] int *count);
#line 20 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\resultset.h"
	[id(2)] HRESULT  GetResult([in] int index, [out,retval] IResultBase **result );
};

[
	object,
	uuid(B94E10D8-08BD-405C-A435-0868DD86CD3C),
	dual,
	helpstring("IAction Interface"),
	pointer_default(unique)
] 
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\action.h"
interface IAction : IActionBase {
#line 20 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\action.h"
	[id(2)] HRESULT  SetActionParameters([in] IParameters *parameters);
#line 22 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\action.h"
	[id(4)] HRESULT  SetProgressBarInfo([in] IProgressBarInfo *pinfo);
#line 24 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\action.h"
	[id(5)] HRESULT  CanDo([in] IResultSet *result, [out,retval] VARIANT_BOOL *can);
#line 26 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\action.h"
	[id(3)] HRESULT  Do([in] IResultSet *input, [out,retval] IResultSet **output );
};

[
	object,
	uuid(63B946E2-2AEE-4034-BA1C-1B4CFD68CEC0),
	dual,
	helpstring("IFunction Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\function.h"
interface IFunction : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\function.h"
	[id(1),local,hidden] HRESULT  GetSystemFunction([out] void **function );
#line 19 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\function.h"
	[id(2),local,hidden] HRESULT  GetSystemFunctionDerivate([out] void **function );
#line 21 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\function.h"
	[id(3)] HRESULT  GetEquations([out,retval] BSTR *equations );
#line 23 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\function.h"
	[id(4)] HRESULT  GetDimension([out,retval] int *dimenstion);
#line 25 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\function.h"
	[id(5)] HRESULT  GetIterations([out,retval] int *iterations);
#line 27 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\function.h"
	[id(6),local,hidden] HRESULT  CreateGraph([out] void **graph );
};

[
	object,
	uuid(AB57FCFD-2759-4E43-8095-34FD20EAAA8B),
	dual,
	helpstring("IComputationParameters Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\computationparameters.h"
interface IComputationParameters : IParameters {
#line 18 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\computationparameters.h"
	[id(5)] HRESULT  GetFunction([out,retval] IFunction **function );
};

[
	object,
	uuid(586FAD2F-D9E4-4A30-A925-345C7E1BDC56),
	dual,
	helpstring("IBoxMethodAction Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\boxmethodaction.h"
interface IBoxMethodAction : IAction {
};

[
	object,
	uuid(EF3F28E7-DA5A-4294-9C12-656D0B7CB74A),
	dual,
	pointer_default(unique)
] 
#line 26 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\boxmethodaction.h"
interface IBoxMethodParameters : IComputationParameters {
#line 28 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\boxmethodaction.h"
	[id(10)] HRESULT  GetFactor([in] int index, [out,retval] int *factor);
#line 30 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\boxmethodaction.h"
	[id(11)] HRESULT  UseDerivate([out,retval] VARIANT_BOOL *out);
};

[
	object,
	uuid(9B7D45A5-77FD-4E97-8C4A-76D3610CC875),
	dual,
	helpstring("IResult Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\result.h"
interface IResult : IResultBase {
};

[
	object,
	uuid(0641C669-B362-48C9-8B73-D02B6E252A9D),
	dual,
	helpstring("IGraphInfo Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
interface IGraphInfo : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
	[id(1)] HRESULT  GetNodes([out,retval] int *value);
#line 19 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
	[id(2)] HRESULT  GetEdges([out,retval] int *value);
#line 21 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
	[id(3)] HRESULT  GetDimension([out,retval] int *value);
#line 23 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
	[id(4)] HRESULT  GetMinimum([in] int index, [out,retval] double *value);
#line 25 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
	[id(5)] HRESULT  GetMaximum([in] int index, [out,retval] double *value);
#line 27 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
	[id(6)] HRESULT  GetGridNumber([in] int index, [out,retval] int *value);
#line 29 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfo.h"
	[id(7)] HRESULT  GetGridSize([in] int index, [out,retval] double *value);
};

[
	object,
	uuid(6E606370-04E2-4BCB-852C-313A7D4BAD15),
	dual,
	helpstring("IGraphResult Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphresult.h"
interface IGraphResult : IResult {
#line 18 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphresult.h"
	[id(10),local,hidden] HRESULT  GetGraph([out] void **graph );
#line 20 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphresult.h"
	[id(12)] HRESULT  GetGraphInfo([out,retval] IGraphInfo **info );
#line 22 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphresult.h"
	[id(13)] HRESULT  IsStrongComponent([out,retval] VARIANT_BOOL *value);
};

[
	object,
	uuid(6ED8D0EA-3E9C-441A-96C6-EEB2AFCBE27D),
	dual,
	helpstring("IWritableGraphResult Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writablegraphresult.h"
interface IWritableGraphResult : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writablegraphresult.h"
	[id(20),local,hidden] HRESULT  SetGraph([in] void **graph , [in] VARIANT_BOOL isStrongComponent);
};

[
	object,
	uuid(A56A15AC-EAC4-4D8B-92FC-84CF84FC4F16),
	dual,
	helpstring("IWritableResultSet Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writableresultset.h"
interface IWritableResultSet : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writableresultset.h"
	[id(5)] HRESULT  AddResult([in] IResultBase *result);
};

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	helpstring("IComponentRegistrar Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\compreg.h"
interface IComponentRegistrar : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\compreg.h"
	[id(1)] HRESULT  Attach([in] BSTR bstrPath);
	[id(2)] HRESULT  RegisterAll();
	[id(3)] HRESULT  UnregisterAll();
	[id(4)] HRESULT  GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)] HRESULT  RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT  UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(FAFD82A9-346E-4BD7-8316-F16B105A4653),
	dual,
	helpstring("ITarjanAction Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\tarjanaction.h"
interface ITarjanAction : IAction {
};

[
	object,
	uuid(8DB63B4A-7E18-4328-9335-419C4CE5A4E5),
	dual,
	helpstring("EmptyParameters"),
	pointer_default(unique)
] 
#line 26 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\tarjanaction.h"
interface ITarjanParameters : IParameters {
#line 29 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\tarjanaction.h"
	[id(1)] HRESULT  NeedEdgeResolve([out,retval] VARIANT_BOOL *result);
};

[
	object,
	uuid(0A8C775B-8E19-4642-B2D7-5BBB437B7B97),
	dual,
	helpstring("IDummy Interface"),
	pointer_default(unique)
] 
#line 22 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\dummy.h"
interface IDummy : IDispatch {
};

[
	object,
	uuid(9B3DA2D8-E279-4552-99F4-13AA066642D5),
	dual,
	helpstring("IWritableFunction Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writablefunction.h"
interface IWritableFunction : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writablefunction.h"
	[id(11)] HRESULT  SetEquations([in] BSTR equations);
#line 19 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writablefunction.h"
	[id(12)] HRESULT  GetLastError([out,retval] BSTR *message );
};

[
	object,
	uuid(5F89F9F3-AB8D-4129-A752-8A4258A8ECE9),
	dual,
	helpstring("IWritableGraphInfo Interface"),
	pointer_default(unique),
	local,
	hidden
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writablegraphinfo.h"
interface IWritableGraphInfo : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writablegraphinfo.h"
	[id(12),local,hidden] HRESULT  AddGraph([in] void **graph );
};

[
	object,
	uuid(F2D78B39-D782-49DE-91B7-771CDA2ED0E0),
	dual,
	helpstring("IKernell Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\kernell.h"
interface IKernell : IDispatch {
#line 18 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\kernell.h"
	[id(3)] HRESULT  GetFunction([out,retval] IFunction **function );
#line 20 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\kernell.h"
	[id(4)] HRESULT  CreateInitialResult([out,retval] IResultBase **result );
};

[
	object,
	uuid(DB255DC6-645A-4D60-A7C6-5D3019C2DBB7),
	dual,
	helpstring("IWritableKernell Interface"),
	pointer_default(unique)
] 
#line 14 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writablekernell.h"
interface IWritableKernell : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\writablekernell.h"
	[id(11)] HRESULT  SetFunction([in] IFunction *function);
};


[ version(1.0), uuid(922445B5-C296-49D0-B69D-45FF70F8CE56), custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a, "{84035475-16DE-4504-ABF2-5C734E46A96A}"), helpstring("MorseKernel2 1.0 Type Library") ]
library MorseKernel2
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

	[
		version(1.0),
		uuid(FDA0C930-C1F5-40C0-A0B6-A978CDA93F50),
		helpstring("BoxMethodAction Class")
	] 
#line 45 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\boxmethodaction.h"
	coclass CBoxMethodAction {
		interface IBoxMethodAction;
		interface IAction;
		interface IActionBase;
	};

	[
		version(1.0),
		uuid(43037E6F-9884-4D5C-BB41-44D582888F9E),
		helpstring("GraphResultImpl Class")
	] 
#line 25 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphresultimpl.h"
	coclass CGraphResultImpl {
		interface IWritableGraphResult;
		interface IGraphResult;
		interface IResult;
		interface IResultBase;
	};

	[
		version(1.0),
		uuid(84035475-16DE-4504-ABF2-5C734E46A96A),
		helpstring("ComponentRegistrar Class")
	] 
#line 33 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\compreg.h"
	coclass CCompReg {
		interface IComponentRegistrar;
	};

	[
		version(1.0),
		uuid(76C75A0A-AC4C-4CA9-8A4E-D8283388C361),
		helpstring("TarjanAction Class")
	] 
#line 45 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\tarjanaction.h"
	coclass CTarjanAction {
		interface ITarjanAction;
		interface IAction;
		interface IActionBase;
	};

	[
		version(1.0),
		uuid(8C3F6AAB-F725-4C70-A92A-7E4BD2A30C23),
		helpstring("Dummy Class")
	] 
#line 39 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\dummy.h"
	coclass CDummy {
		interface IDummy;
		interface IAction;
		interface IActionBase;
		interface IResult;
		interface IResultBase;
		interface IResultBase;
		interface IResultSet;
		interface IFunction;
		interface IBoxMethodParameters;
		interface IComputationParameters;
		interface IParameters;
		interface ITarjanParameters;
		interface IParameters;
	};

	[
		version(1.0),
		uuid(FDFB8D0E-74FF-439C-A13B-4A39387B7037),
		helpstring("FunctionImpl Class")
	] 
#line 24 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\functionimpl.h"
	coclass CFunctionImpl {
		interface IFunction;
		interface IWritableFunction;
	};

	[
		version(1.0),
		uuid(1FCB1E52-C321-4E44-8BA6-83DA8C532365),
		helpstring("GraphInfoImpvffffl Class")
	] 
#line 23 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\graphinfoimpl.h"
	coclass CGraphInfoImpl {
		interface IWritableGraphInfo;
		interface IGraphInfo;
	};

	[
		version(1.0),
		uuid(5FAAF083-60CC-4A9B-AAC0-4FDB29047B08),
		helpstring("ResultSetImpl Class")
	] 
#line 23 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\resultsetimpl.h"
	coclass CResultSetImpl {
		interface IResultSet;
		interface IWritableResultSet;
	};

	[
		version(1.0),
		uuid(96E908D0-29BD-423D-8CA8-9F4343C796A0),
		helpstring("KernellImpl Class")
	] 
#line 20 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernel2\\kernellimpl.h"
	coclass CKernellImpl {
		interface IKernell;
		interface IWritableKernell;
	};

}

