//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.1433
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace DSIS.CellImageBuilder.BoxMethod {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:shemas-dsis-org:box-method-settings")]
    [System.Xml.Serialization.XmlRootAttribute("BoxMethod-Settings", Namespace="urn:shemas-dsis-org:box-method-settings", IsNullable=false)]
    public partial class XsdBoxMethodSettings {
        
        private double epsField;
        
        public XsdBoxMethodSettings() {
            this.epsField = 0.1;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0.1)]
        public double Eps {
            get {
                return this.epsField;
            }
            set {
                this.epsField = value;
            }
        }
    }
}
