using System.Collections.Generic;
using DSIS.Core.Builders;
using DSIS.IntegerCoordinates.Tests;
using NUnit.Framework;

namespace DSIS.IntegerCoordinates.Generic
{
  public abstract class CellConnectionAdapterTwoDimBaseTest<T,Q> : CellConnectionAdapterTestBase<T,Q>
    where T : IIntegerCoordinateSystem<Q>
    where Q : IIntegerCoordinate<Q>
  {
    private void DoTestAbstract(DoBuild bld, string assert)
    {
      double[] sleft = {0, 0};
      double[] sright = {10, 10};
      long[] sgrid = {10, 10};

      mySpace = new MockSystemSpace(2, sleft, sright, sgrid);
      T ics = CoordinateSystem();

      myIcs = ics;
      List<Q> data = DoTest(ics, bld);

      TwoDimCoordinateAssert.Assert(ics, data, assert);
      myIcs = default(T);
    }

    protected virtual T CoordinateSystem()
    {
      return IntegerCoordinateSystemFactory.CreateCoordinateSystem<T,Q>(mySpace);
    }

    private void DoTestAddCellToRect(double[] left, double[] right, string assert)
    {
      double[] eps = {0, 0};

      DoTestAbstract(
        delegate(ICellConnectionBuilder<Q> ad)
          {
            IRectProcessor<Q> ps = myIcs.ProcessorFactory.CreateRectProcessor(eps);
            
            ad.ConnectToMany(default(Q), ps.ConnectCellToRect(left, right));
          }, assert);
    }

    private void DoTestAddCellToPointRadius(double[] point, double[] perc, string assert)
    {
      DoTestAbstract(
        delegate(ICellConnectionBuilder<Q> ad)
          {
            IRadiusProcessor<Q> ps = myIcs.ProcessorFactory.CreateRadiusProcessor();
            ad.ConnectToMany(default(Q), ps.ConnectCellToRadius(point, perc));
          },
        assert);
    }

    private void DoTestAddCellToPointOverlap(double[] point, double[] perc, string assert)
    {
      DoTestAbstract(
        delegate(ICellConnectionBuilder<Q> ad)
          {
            IPointProcessor<Q> ps = myIcs.ProcessorFactory.CreateOverlapedPointProcessor(perc);
            ad.ConnectToMany(default(Q), ps.AddPoint(point));
          },
        assert);
    }

    private void DoTestAddCellToPoint(double[] point, string assert)
    {
      DoTestAbstract(
        delegate(ICellConnectionBuilder<Q> ad)
          {
            IPointProcessor<Q> ps = myIcs.ProcessorFactory.CreatePointProcessor();
            ad.ConnectToMany(default(Q), ps.AddPoint(point));
          },
        assert);
    }

    [Test]
    public void Test_01()
    {
      DoTestAddCellToRect(new double[] {0, 0}, new double[] {10, 10},
                          @"-------------------
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
xxxxxxxxxx
-------------------
");
    }


    [Test]
    public void Test_02()
    {
      DoTestAddCellToRect(new double[] {1, 0}, new double[] {2, 2},
                          @"-------------------
..........
xxx.......
xxx.......
..........
..........
..........
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_03()
    {
      DoTestAddCellToRect(new double[] {0.01, 0.02}, new double[] {0.01, 0.02},
                          @"-------------------
x.........
..........
..........
..........
..........
..........
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_04()
    {
      DoTestAddCellToPointRadius(new double[] {0.001, 0.0002}, new double[] {0.1, 0.2},
                           @"-------------------
x.........
..........
..........
..........
..........
..........
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_05()
    {
      DoTestAddCellToPointRadius(new double[] {1.001, 1.0002}, new double[] {0.1, 0.2},
                           @"-------------------
xx........
xx........
..........
..........
..........
..........
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_06()
    {
      DoTestAddCellToPointRadius(new double[] {1.901, 1.0002}, new double[] {0.1, 0.1},
                           @"-------------------
..........
xx........
xx........
..........
..........
..........
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_07()
    {
      DoTestAddCellToPointRadius(new double[] {5, 5}, new double[] {0.1, 0.1},
                           @"-------------------
..........
..........
..........
..........
....xx....
....xx....
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_08()
    {
      DoTestAddCellToPointRadius(new double[] {5, 5}, new double[] {0, 0},
                           @"-------------------
..........
..........
..........
..........
..........
.....x....
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_09()
    {
      DoTestAddCellToPointOverlap(new double[] {5, 5}, new double[] {0.2, 0.2},
                           @"-------------------
..........
..........
..........
..........
....xx....
....xx....
..........
..........
..........
..........
-------------------
");
    }


    [Test]
    public void Test_10()
    {
      DoTestAddCellToPointOverlap(new double[] { 5.3, 5.7 }, new double[] { 0.2, 0.2 },
                           @"-------------------
..........
..........
..........
..........
..........
.....x....
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_11()
    {
      DoTestAddCellToPointOverlap(new double[] { 5.0, 5.7 }, new double[] { 0.2, 0.2 },
                           @"-------------------
..........
..........
..........
..........
.....x....
.....x....
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_12()
    {
      DoTestAddCellToPointOverlap(new double[] { 5.9, 5.7 }, new double[] { 0.2, 0.2 },
                           @"-------------------
..........
..........
..........
..........
..........
.....x....
.....x....
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_13()
    {
      DoTestAddCellToPointOverlap(new double[] { 5.5, 5.9 }, new double[] { 0.2, 0.2 },
                           @"-------------------
..........
..........
..........
..........
..........
.....xx...
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_14()
    {
      DoTestAddCellToPointOverlap(new double[] { 5.5, 5.1 }, new double[] { 0.2, 0.2 },
                           @"-------------------
..........
..........
..........
..........
..........
....xx....
..........
..........
..........
..........
-------------------
");
    }

    [Test]
    public void Test_110()
    {
      DoTestAddCellToPoint(new double[] {5, 5},
                           @"-------------------
..........
..........
..........
..........
..........
.....x....
..........
..........
..........
..........
-------------------
");
    }


  }
}