import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\prsht.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\mshtml.idl";
import "c:\program files\microsoft visual studio .net 2003\vc7\platformsdk\include\dimm.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\mshtmhst.idl";
import "c:\program files\microsoft visual studio .net 2003\vc7\platformsdk\include\docobj.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\exdisp.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\objsafe.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	helpstring("IComponentRegistrar Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\compreg.h"
interface IComponentRegistrar : IDispatch {
#line 17 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\compreg.h"
	[id(1)] HRESULT  Attach([in] BSTR bstrPath);
	[id(2)] HRESULT  RegisterAll();
	[id(3)] HRESULT  UnregisterAll();
	[id(4)] HRESULT  GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)] HRESULT  RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT  UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(35435412-4462-4A3D-A9C8-CEB11AC900EE),
	dual,
	helpstring("IMorseKernelVisualizationDirect3D Interface"),
	pointer_default(unique)
] 
#line 13 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirect3d.h"
interface IMorseKernelVisualizationDirect3D : IDispatch {
#line 16 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirect3d.h"
	[id(1)] HRESULT  MoveLeftAtom();
#line 18 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirect3d.h"
	[id(2)] HRESULT  MoveRightAtom();
#line 20 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirect3d.h"
	[id(3)] HRESULT  MoveUpAtom();
#line 22 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirect3d.h"
	[id(4)] HRESULT  MoveDownAtom();
#line 24 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirect3d.h"
	[id(5)] HRESULT  ZoomOutAtom();
#line 26 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirect3d.h"
	[id(6)] HRESULT  ZoomInAtom();
#line 28 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirect3d.h"
	[id(7)] HRESULT  CenterView();
#line 31 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirect3d.h"
	[id(8),local] HRESULT  SetGraph([in] void **graph );
#line 34 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirect3d.h"
	[id(9)] HRESULT  SetTestGraph();
};

[
	object,
	uuid(ADE7B805-2B13-46CC-9F90-7E4E6D1B9384),
	dual,
	helpstring("IMorseKernelVisualizationDirectGraph3D Interface"),
	pointer_default(unique)
] 
#line 18 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirectgraph3d.h"
interface IMorseKernelVisualizationDirectGraph3D : IMorseKernelVisualizationDirect3D {
#line 21 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirectgraph3d.h"
	[id(54)] HRESULT  MoveFromEye([in] DOUBLE x, [in] DOUBLE y, [in] DOUBLE z);
#line 24 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirectgraph3d.h"
	[id(55)] HRESULT  SetEyeFrom([in] FLOAT x, [in] FLOAT y, [in] FLOAT z);
#line 26 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirectgraph3d.h"
	[id(56)] HRESULT  SetEyeTo([in] FLOAT x, [in] FLOAT y, [in] FLOAT z);
#line 28 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirectgraph3d.h"
	[id(57)] HRESULT  Rotate([in] FLOAT onX, [in] FLOAT onY, [in] FLOAT onZ);
};

[
	object,
	uuid(31146F99-AA89-4E63-94B2-CFF1358E46ED),
	dual,
	helpstring("IMorseKernelVisualizationDirectGraph2D Interface"),
	pointer_default(unique)
] 
#line 15 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationgraph2d.h"
interface IMorseKernelVisualizationDirectGraph2D : IMorseKernelVisualizationDirect3D {
};


[ version(1.0), uuid(EC4C473F-66E4-4129-BE42-48D9BEF71D34), custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a, "{C5F4E1EE-5450-4DED-B0A0-97941189B524}"), helpstring("MorseKernelVisualizationATL 1.0 Type Library") ]
library MorseKernelVisualizationATL
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

	[
		version(1.0),
		uuid(C5F4E1EE-5450-4DED-B0A0-97941189B524),
		helpstring("ComponentRegistrar Class")
	] 
#line 33 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\compreg.h"
	coclass CCompReg {
		interface IComponentRegistrar;
	};

	[
		uuid(FE6F9A99-FF69-44D9-89AD-685E6C7303CA),
		helpstring("_IMorseKernelVisualizationDirect3DEvents Interface")
	] 
#line 46 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirect3d.h"
	dispinterface _IMorseKernelVisualizationDirect3DEvents {
	properties:

	methods:
#line 48 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirect3d.h"
		[id(1)] HRESULT  ActiveLoop([in] int length);
#line 51 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirect3d.h"
		[id(2)] HRESULT  OnMouseMoveFloat([in] double x1, [in] double x2, [in] double x3);
	};

	[
		version(1.1),
		uuid(3CF9772B-CC75-4596-A5EC-903D6ABD4983),
		helpstring("MorseKernelVisualizationDirectGraph3D Class")
	] 
#line 44 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationdirectgraph3d.h"
	coclass CMorseKernelVisualizationDirectGraph3D {
		interface IMorseKernelVisualizationDirectGraph3D;
		interface IMorseKernelVisualizationDirect3D;
		[default, source]	interface _IMorseKernelVisualizationDirect3DEvents;
	};

	[
		version(1.0),
		uuid(2BBDCC1B-8356-4536-9C86-0CBABD9158B0),
		helpstring("MorseKernelVisualizationDirect3D Class")
	] 
#line 32 "e:\\projects\\morse\\dotnetproject\\morse\\dotnet\\morsekernelvisualizationatl\\morsekernelvisualizationgraph2d.h"
	coclass CMorseKernelVisualizationDirectGraph2D {
		interface IMorseKernelVisualizationDirectGraph2D;
		interface IMorseKernelVisualizationDirect3D;
		[default, source]	interface _IMorseKernelVisualizationDirect3DEvents;
	};

}

