//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MorseKernelVisualizationATL.rc
//
#define IDS_PROJNAME                    100
#define IDR_MORSEKERNELVISUALIZATIONATL 101
#define IDB_MORSEKERNELVISUALIZATIONDIRECT3D 102
#define IDH_MORSEKERNELVISUALIZATIONDIRECT3D 103
#define IDB_MORSEKERNELVISUALIZATIONGDI 104
#define IDH_MORSEKERNELVISUALIZATIONGDI 105
#define IDB_MORSEKERNELVISUALIZATIONDIRECTGRAPH3D 106
#define IDH_MORSEKERNELVISUALIZATIONDIRECTGRAPH3D 108

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
