//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace DSIS.CellImageBuilder.BoxMethod {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:shemas-dsis-org:box-method-settings")]
    [System.Xml.Serialization.XmlRootAttribute("BoxMethod-Settings", Namespace="urn:shemas-dsis-org:box-method-settings", IsNullable=false)]
    public class XsdBoxMethodSettings {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0.1)]
        public System.Double Eps = 0.1;
    }
}
